name: Deploy to Railway

on:
  push:
    branches:
      - master  # Runs only when pushing to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Deploy to Railway
      - name: Deploy to Railway
        run: railway up --service nestjs-personal-expense-tracker
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
